In [1]:
# Import the basic libraries to build our own neural network model
import numpy as np
import pandas as pd

In [ ]:
# Initialize simple paramters of same scale and if possible small values so the model converges faster 
df = pd.DataFrame(
                    [
                        [8,8,4],
                        [7,9,5],
                        [6,10,6],
                        [5,12,7]
                    ]
                    , columns = ['cgpa', 'profile_score', 'lpa']
                )

In [4]:
df # Check the dataset

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [46]:
# A utility function to initialize values to the parameter based on the list passed
# The passed list contains : pair of each matrix dimensions for the weights and bias

def initialize_parameters(layer_dims):

  np.random.seed(3)
  parameters = {}
  L = len(layer_dims) # This is basically the number of layers in the neural network

  for l in range(1, L): # We start with 1 because we need it 

    # print(f'\n Layer : {l}\n')

    parameters['W' + str(l)] = np.ones(
                                        (layer_dims[l-1], layer_dims[l]) # The shape of weight matrix for layer l
                                      )*0.1
    
    parameters['b' + str(l)] = np.zeros(
                                          (layer_dims[l], 1) # The shape of bias matrix for layer l
                                        )

    # print(f'\n Weights : \n {parameters['W' + str(l)]} \n ')
    # print(f'\n Bias : \n {parameters['b' + str(l)]} \n ')

  return parameters

In [33]:
parameters = initialize_parameters([2,2,1])
# This means that the first weight matrix will be having layer_dims[1-1] = 2 rows and layer_dims[1] =2 columns
# No of bias is equal to layer_dims[1-1] = 2 rows and 1 column (Fixed)

# Next layer will have weight layer_dims[2-1] = 2 rows and layer_dims[2] = 1 column
# No of bias is equal to 1 row and 1 column (Fixed)


 Layer : 1


 Weights : 
 [[0.1 0.1]
 [0.1 0.1]] 
 

 Bias : 
 [[0.]
 [0.]] 
 

 Layer : 2


 Weights : 
 [[0.1]
 [0.1]] 
 

 Bias : 
 [[0.]] 
 


In [36]:
len(parameters) // 2 # <-- No of layers in neural network

2

In [31]:
# A simple function that passess the linear dot product of weights and Inputs from previous neuron wih bias added to form Z
# It will be used by neurons to calculate the output of them using weights,bias and input

def linear_forward(O_prev, W, b):

  # Z = np.dot(transpose_of_weight_matrix,input_to_neuron) + bias

  Z = np.dot(W.T, O_prev) + b

  return Z

In [51]:
# Forward Propogation using parameters that are made from the utiltiy function before and the matrix X as input

def L_layer_forward(X, parameters):

  A = X # Input to Input layer 1
  L = len(parameters) // 2 # number of layers in the neural network

  for l in range(1, L+1): # An additional loop to calculate the final output

    A_prev = A # In the current loop the previous loop's value becomes the previous_output

    # Fetching the parameters from the paramters hashmap using the layer index
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]

    # Pass the matrices to the linear forward utility function so it returns the output(Z)
    A = linear_forward(A_prev, Wl, bl)


  return A,A_prev # In the end the output will be returned with the output of the previous layer 

In [52]:
# Extract a list of row from the data as X and y to evaluate the model
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

In [53]:
# Parameter initialization with the initialization function
parameters = initialize_parameters([2,2,1])

# Also pass the X tuple here at first to understand how the forward propogation works for a single row
y_hat,A1 = L_layer_forward(X, parameters)

In [61]:
df.iloc[0,:]

cgpa             8
profile_score    8
lpa              4
Name: 0, dtype: int64

In [ ]:
y_hat # <-- The prediction for the following above row

array([[0.32]])

In [64]:
A1 # <-- Output of the previous layer

array([[1.6],
       [1.6]])

In [ ]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [ ]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]), 'W2': array([[0.111776],
        [0.111776]]), 'b1': array([[0.00082267],
        [0.00082267]]), 'b2': array([[0.119136]])}

In [ ]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[1][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.11458955, 0.1168776 ],
        [0.11458955, 0.1168776 ]]), 'W2': array([[0.12712927],
        [0.12712927]]), 'b1': array([[0.0019667],
        [0.0019667]]), 'b2': array([[0.13612818]])}

In [ ]:
X = df[['cgpa', 'profile_score']].values[2].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[2][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.12409711, 0.13272353],
        [0.12412266, 0.13276611]]), 'W2': array([[0.14692424],
        [0.14731907]]), 'b1': array([[0.00355129],
        [0.00355555]]), 'b2': array([[0.15810417]])}

In [ ]:
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[3][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.13482804, 0.15847776],
        [0.1349909 , 0.15884991]]), 'W2': array([[0.17312488],
        [0.17534027]]), 'b1': array([[0.00569748],
        [0.0057292 ]]), 'b2': array([[0.18773702]])}

In [ ]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  25.321744156025517
Epoch -  2 Loss -  18.320004165722047
Epoch -  3 Loss -  9.473661050729628
Epoch -  4 Loss -  3.2520938634031613
Epoch -  5 Loss -  1.3407132589299962


{'W1': array([[0.26507636, 0.38558861],
        [0.27800387, 0.40980287]]), 'W2': array([[0.41165744],
        [0.48302736]]), 'b1': array([[0.02749056],
        [0.02974394]]), 'b2': array([[0.48646246]])}