In [4]:
import torch # Torch Module

In [6]:
# We explicity add a dedcimal because we want the numeric values to be floating numbers and not integers.
# This matters because weights, gradients, and most neural network math need floats, not integers.
x = torch.tensor(
                  [[2., 1., 0., 3.],
                   [1., 0., 2., 1.],
                   [3., 2., 1., 0.],
                   [0., 1., 3., 2.]]
)

In [ ]:
""" 
    If shapes don't align for an operation, it throws an error immediately, rather than silently computing something wrong.
    Checking .shape after every operation, especially while learning, is not optional busywork — 
    it's how you verify your mental model of what just happened matches what actually happened.
"""

In [9]:
print(x.shape)      # torch.Size([4, 4])
print(x.shape[0])   # 4  — number of rows
print(x.dim())       # 2  — number of dimensions

torch.Size([4, 4])
4
2


In [ ]:
# Basic Operations : 

a = torch.tensor([1., 2., 3.])
b = torch.tensor([4., 5., 6.])

print(a + b)        # tensor([5., 7., 9.])   — element-wise addition 
print(a * b)        # tensor([4., 10., 18.]) — element-wise multiplication, NOT dot product ( Hadamard Product )
print(torch.dot(a, b))  # tensor(32.)         — actual dot product: 1×4+2×5+3×6=32

tensor([5., 7., 9.])
tensor([ 4., 10., 18.])
tensor(32.)


In [11]:
# Matrix multiplication —  z = W·x calculation
W = torch.tensor([[0.5, -1.0]])   # shape (1, 2) — our FC layer's weight from the CNN exercise
flat = torch.tensor([[3.0, 1.0]]) # shape (1, 2) — our flattened pooled values

# Matrix multiply: (1,2) can't directly multiply (1,2) — need to transpose
z = flat @ W.T + 0.2
print(z)   # tensor([[0.7000]])

tensor([[0.7000]])
