In [48]:
import torch

In [49]:
print(torch.__version__)

2.11.0+cu128


In [50]:
device = torch.device('cuda') # This step enables us to run the tensors using our vgpu

A tensor is a multi-dimensional array of data, a geometric object describing linear relations, and a generalization of scalars, vectors, and matrices into higher **dimensions**.

In [51]:
x = torch.tensor([[1,2,3,4,5]],device=device) # A simple tensor in torch where we directly pass values to create a tensor
# This looks like an overhead but is incredibly useful when doing complex tasks on n-dimensional hyperplanes.

In [52]:
x

tensor([[1, 2, 3, 4, 5]], device='cuda:0')

In [53]:
type(x) # The type is a tensor

torch.Tensor

In [54]:
x.shape # The shape is 1,5 and is 2d tensor

torch.Size([1, 5])

In [55]:
# Do not confuse this with a 1d tensor which are just points in a line :
torch.tensor([1,2,3,4,5]).shape # Notice that this is a vector and is 1D.

torch.Size([5])

In [56]:
# And this below is a scaler : 0D
torch.tensor(5).shape # See there is no size ? That is because it is a 0D tensor.

torch.Size([])

In [57]:
# Another examples of higher dimensional tensors are :

# Configuration: [Channels (RGB), Height, Width]
channels = 3
height = 256
width = 256

# Create the 3D tensor with random pixel values between 0 and 1
image_tensor = torch.rand(channels, height, width, device=device)
# We will be covering rand class later for now think of it a tool that creates random numbers by passed dimensions

# Check the dimensions
print(f"Tensor Shape: {image_tensor.shape}")
print(f"Number of dimensions: {image_tensor.ndim}")


Tensor Shape: torch.Size([3, 256, 256])
Number of dimensions: 3


In [58]:
# An example of 4D tensor is this image being unsqueezed and passed to as batches for convolution.
image_tensor.unsqueeze(0).shape

torch.Size([1, 3, 256, 256])

In [59]:
# An example of 5D tensor is a video which is collection of these 4D tensor

In [60]:
# Now following we will look at some other ways to instantiate matrix , other than implicitly specifying values.

In [90]:
# For all these ways we will use a simple size of :
size = (3,3) # Each of this ways share the size parameter

In [65]:
torch.empty(size) # Instantiation of an empty tensor with the passed shape
# This function allocates the the allocated size tensor whose values can be anything that already exist on that memory space.

tensor([[3.6113e-30, 4.5602e-41, 7.4993e-20],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [66]:
torch.zeros(size) # Instantiate a tensor with values filled : 0

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [67]:
torch.ones(size) # Instantiate a tensor with values filled : 1

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [70]:
torch.rand(size) # Instantiate a tensor with values filled : Random floating numbers

tensor([[0.4750, 0.9374, 0.8265],
        [0.3117, 0.3345, 0.1706],
        [0.1863, 0.7688, 0.1368]])

In [72]:
torch.tensor((1,2,3)) # Passing a tuple to create a tensor 1D vector

tensor([1, 2, 3])

In [74]:
torch.eye(5) # Create an idenitity matrix with the passed n value

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [80]:
torch.linspace(start=0,end=10,steps=100) # Creates a 2D vector where we pass the starting and the ending point with the step value between these

tensor([ 0.0000,  0.1010,  0.2020,  0.3030,  0.4040,  0.5051,  0.6061,  0.7071,
         0.8081,  0.9091,  1.0101,  1.1111,  1.2121,  1.3131,  1.4141,  1.5152,
         1.6162,  1.7172,  1.8182,  1.9192,  2.0202,  2.1212,  2.2222,  2.3232,
         2.4242,  2.5253,  2.6263,  2.7273,  2.8283,  2.9293,  3.0303,  3.1313,
         3.2323,  3.3333,  3.4343,  3.5354,  3.6364,  3.7374,  3.8384,  3.9394,
         4.0404,  4.1414,  4.2424,  4.3434,  4.4444,  4.5455,  4.6465,  4.7475,
         4.8485,  4.9495,  5.0505,  5.1515,  5.2525,  5.3535,  5.4545,  5.5556,
         5.6566,  5.7576,  5.8586,  5.9596,  6.0606,  6.1616,  6.2626,  6.3636,
         6.4646,  6.5657,  6.6667,  6.7677,  6.8687,  6.9697,  7.0707,  7.1717,
         7.2727,  7.3737,  7.4747,  7.5758,  7.6768,  7.7778,  7.8788,  7.9798,
         8.0808,  8.1818,  8.2828,  8.3838,  8.4848,  8.5859,  8.6869,  8.7879,
         8.8889,  8.9899,  9.0909,  9.1919,  9.2929,  9.3939,  9.4949,  9.5960,
         9.6970,  9.7980,  9.8990, 10.00

In [88]:
torch.full((2,2),0.5) # Pass in the shape as tuple and we make it such that all the values are instantiated with a single value

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])

In [97]:
# We can also do this :
n=3.14
(n)*torch.ones(size,dtype=torch.float32)

tensor([[3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400]])

In [104]:
# Now we can also create using all these but with the dimensions of other tensor
# 1. An existing tensor (e.g., a 2x3 matrix)
existing_tensor = torch.rand(2, 3)

# 2. Create a new tensor with the same shape, filled with 5.5
new_tensor = torch.full_like(existing_tensor, 5.5)

 # We passed in another tensor shape and using that shape we created similar shaped tensor but with our values
existing_tensor.shape,new_tensor.shape

(torch.Size([2, 3]), torch.Size([2, 3]))