In [1]:
import torch

In [2]:
print(torch.__version__)

2.11.0+cu128


In [3]:
device = torch.device('cuda') # This step enables us to run the tensors using our vgpu

In [4]:
device

device(type='cuda')

A tensor is a multi-dimensional array of data, a geometric object describing linear relations, and a generalization of scalars, vectors, and matrices into higher **dimensions**.

In [5]:
x = torch.tensor([[1,2,3,4,5]],
                 device=device
                 ) # A simple tensor in torch where we directly pass values to create a tensor
# This looks like an overhead but is incredibly useful when doing complex tasks on n-dimensional hyperplanes.

In [6]:
x

tensor([[1, 2, 3, 4, 5]], device='cuda:0')

In [7]:
type(x) # The type is a tensor

torch.Tensor

In [8]:
x.shape # The shape is 1,5 and is 2d tensor

torch.Size([1, 5])

In [9]:
# Do not confuse this with a 1d tensor which are just points in a line :
torch.tensor([1,2,3,4,5]).shape # Notice that this is a vector and is 1D.

torch.Size([5])

In [10]:
# And this below is a scaler : 0D
torch.tensor(5).shape # See there is no size ? That is because it is a 0D tensor.

torch.Size([])

In [11]:
# Another examples of higher dimensional tensors are :

# Configuration: [Channels (RGB), Height, Width]
channels = 3
height = 256
width = 256

# Create the 3D tensor with random pixel values between 0 and 1
image_tensor = torch.rand(channels, height, width)
# We will be covering rand class later for now think of it a tool that creates random numbers by passed dimensions

# Check the dimensions
print(f"Tensor Shape: {image_tensor.shape}")
print(f"Number of dimensions: {image_tensor.ndim}")


Tensor Shape: torch.Size([3, 256, 256])
Number of dimensions: 3


In [12]:
# An example of 4D tensor is this image being unsqueezed and passed to as batches for convolution.
image_tensor.unsqueeze(0).shape

torch.Size([1, 3, 256, 256])

In [13]:
# An example of 5D tensor is a video which is collection of these 4D tensor

In [14]:
# Now following we will look at some other ways to instantiate matrix , other than implicitly specifying values.

In [15]:
# For all these ways we will use a simple size of :
size = (3,3) # Each of this ways share the size parameter

In [16]:
torch.empty(size) # Instantiation of an empty tensor with the passed shape
# This function allocates the the allocated size tensor whose values can be anything that already exist on that memory space.

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [17]:
torch.zeros(size) # Instantiate a tensor with values filled : 0

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [18]:
torch.ones(size) # Instantiate a tensor with values filled : 1

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [19]:
torch.rand(size) # Instantiate a tensor with values filled : Random floating numbers

tensor([[0.4726, 0.0122, 0.4905],
        [0.5255, 0.1963, 0.7332],
        [0.3025, 0.4332, 1.0000]])

In [20]:
torch.tensor((1,2,3)) # Passing a tuple to create a tensor 1D vector

tensor([1, 2, 3])

In [21]:
torch.eye(5) # Create an idenitity matrix with the passed n value

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [22]:
torch.linspace(start=0,end=10,steps=100) # Creates a 2D vector where we pass the starting and the ending point with the step value between these

tensor([ 0.0000,  0.1010,  0.2020,  0.3030,  0.4040,  0.5051,  0.6061,  0.7071,
         0.8081,  0.9091,  1.0101,  1.1111,  1.2121,  1.3131,  1.4141,  1.5152,
         1.6162,  1.7172,  1.8182,  1.9192,  2.0202,  2.1212,  2.2222,  2.3232,
         2.4242,  2.5253,  2.6263,  2.7273,  2.8283,  2.9293,  3.0303,  3.1313,
         3.2323,  3.3333,  3.4343,  3.5354,  3.6364,  3.7374,  3.8384,  3.9394,
         4.0404,  4.1414,  4.2424,  4.3434,  4.4444,  4.5455,  4.6465,  4.7475,
         4.8485,  4.9495,  5.0505,  5.1515,  5.2525,  5.3535,  5.4545,  5.5556,
         5.6566,  5.7576,  5.8586,  5.9596,  6.0606,  6.1616,  6.2626,  6.3636,
         6.4646,  6.5657,  6.6667,  6.7677,  6.8687,  6.9697,  7.0707,  7.1717,
         7.2727,  7.3737,  7.4747,  7.5758,  7.6768,  7.7778,  7.8788,  7.9798,
         8.0808,  8.1818,  8.2828,  8.3838,  8.4848,  8.5859,  8.6869,  8.7879,
         8.8889,  8.9899,  9.0909,  9.1919,  9.2929,  9.3939,  9.4949,  9.5960,
         9.6970,  9.7980,  9.8990, 10.00

In [23]:
torch.full((2,2),0.5) # Pass in the shape as tuple and we make it such that all the values are instantiated with a single value

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])

In [24]:
# We can also do this :
n=3.14
(n)*torch.ones(size,dtype=torch.float32)

tensor([[3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400]])

In [25]:
# Now we can also create using all these but with the dimensions of other tensor
# 1. An existing tensor (e.g., a 2x3 matrix)
existing_tensor = torch.rand(2, 3)

# 2. Create a new tensor with the same shape, filled with 5.5
new_tensor = torch.full_like(existing_tensor, 5.5)

 # We passed in another tensor shape and using that shape we created similar shaped tensor but with our values
existing_tensor.shape,new_tensor.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [26]:
# Now let us apply some math functions on a singe tensor

In [27]:
x = torch.rand((2,2))

In [28]:
x

tensor([[0.1504, 0.3091],
        [0.8548, 0.7356]])

In [29]:
x+2

tensor([[2.1504, 2.3091],
        [2.8548, 2.7356]])

In [30]:
x-2

tensor([[-1.8496, -1.6909],
        [-1.1452, -1.2644]])

In [31]:
x/2

tensor([[0.0752, 0.1546],
        [0.4274, 0.3678]])

In [32]:
x//2

tensor([[0., 0.],
        [0., 0.]])

In [33]:
2*x

tensor([[0.3007, 0.6182],
        [1.7095, 1.4712]])

In [34]:
x**3

tensor([[0.0034, 0.0295],
        [0.6245, 0.3980]])

In [35]:
# We can apply the same with another tensor
y = torch.rand((2,2))

In [36]:
y

tensor([[0.8131, 0.8696],
        [0.7539, 0.2134]])

In [37]:
x+y

tensor([[0.9635, 1.1787],
        [1.6087, 0.9490]])

In [38]:
x-y

tensor([[-0.6628, -0.5604],
        [ 0.1008,  0.5221]])

In [39]:
x*y

tensor([[0.1223, 0.2688],
        [0.6444, 0.1570]])

In [40]:
x/y

tensor([[0.1849, 0.3555],
        [1.1337, 3.4462]])

In [41]:
x//y

tensor([[0., 0.],
        [1., 3.]])

In [42]:
x**y

tensor([[0.2142, 0.3603],
        [0.8884, 0.9366]])

In [43]:
# Now let us look at some reduction operations :

In [44]:
x = torch.randn((3,3))

In [45]:
x

tensor([[-0.1938, -0.8750,  0.3477],
        [-1.4243, -0.9009, -0.5536],
        [ 0.9336,  0.9268, -1.3523]])

In [46]:
# Calculate the absolute value of each element
x.abs()

tensor([[0.1938, 0.8750, 0.3477],
        [1.4243, 0.9009, 0.5536],
        [0.9336, 0.9268, 1.3523]])

In [47]:
# Calculate the sum of all elements in the tensor
x.sum()

tensor(-3.0917)

In [48]:
# Round each element to the nearest integer
x.round()

tensor([[-0., -1.,  0.],
        [-1., -1., -1.],
        [ 1.,  1., -1.]])

In [49]:
# Negate each element in the tensor
x.negative()

tensor([[ 0.1938,  0.8750, -0.3477],
        [ 1.4243,  0.9009,  0.5536],
        [-0.9336, -0.9268,  1.3523]])

In [50]:
# Compute the ceiling of each element (smallest integer greater than or equal to the element)
x.ceil()

tensor([[-0., -0.,  1.],
        [-1., -0., -0.],
        [ 1.,  1., -1.]])

In [51]:
# Compute the floor of each element (largest integer less than or equal to the element)
x.floor()

tensor([[-1., -1.,  0.],
        [-2., -1., -1.],
        [ 0.,  0., -2.]])

In [52]:
# Clamp tensor values to a specified range (0.1 to 0.2)
x.clamp(0.1,0.2)

tensor([[0.1000, 0.1000, 0.2000],
        [0.1000, 0.1000, 0.1000],
        [0.2000, 0.2000, 0.1000]])

In [53]:
# Now some statistical operations we use daily

In [54]:
# Calculate the mean of all elements in the tensor
x.mean()

tensor(-0.3435)

In [55]:
# Calculate the variance of all elements in the tensor
x.var()

tensor(0.8210)

In [56]:
# Calculate the standard deviation of all elements in the tensor
x.std()

tensor(0.9061)

In [57]:
# Find the maximum value in the tensor
x.max()

tensor(0.9336)

In [58]:
# Find the minimum value in the tensor
x.min()

tensor(-1.4243)

In [59]:
# Calculate the product of all elements in the tensor
x.prod()

tensor(0.0490)

In [60]:
# Find the median value of the tensor
x.median()

tensor(-0.5536)

In [61]:
# NOW some matrix operations

In [62]:
# Initialize two 3x3 tensors with random values
mat_a,mat_b = torch.randn((3,3)),torch.randn((3,3))

In [63]:
mat_a

tensor([[-0.3650, -1.2520, -0.0822],
        [ 0.3357,  2.6760, -0.6013],
        [ 0.0034,  2.3244,  0.8553]])

In [64]:
mat_b

tensor([[-0.2372, -0.2766,  0.0273],
        [-0.7830,  2.2765, -0.1121],
        [ 0.4027, -0.5602,  0.2760]])

In [65]:
# Perform matrix multiplication between mat_a and mat_b
mat_a.matmul(mat_b)

tensor([[ 1.0338, -2.7034,  0.1077],
        [-2.4170,  6.3361, -0.4567],
        [-1.4763,  4.8114, -0.0243]])

In [66]:
# Calculate the determinant of matrix a
mat_a.det()

tensor(-1.0467)

In [67]:
# Now we can also use some built in functions on the tensors directly.

In [68]:
mat_b

tensor([[-0.2372, -0.2766,  0.0273],
        [-0.7830,  2.2765, -0.1121],
        [ 0.4027, -0.5602,  0.2760]])

In [69]:
# Calculate the exponential of each element in mat_b
mat_b.exp()

tensor([[0.7889, 0.7584, 1.0277],
        [0.4570, 9.7429, 0.8940],
        [1.4959, 0.5711, 1.3178]])

In [70]:
# Calculate the natural logarithm of each element in mat_b
mat_b.log()

tensor([[    nan,     nan, -3.6014],
        [    nan,  0.8227,     nan],
        [-0.9096,     nan, -1.2874]])

In [71]:
# Apply the sigmoid function to each element in mat_b
mat_b.sigmoid()

tensor([[0.4410, 0.4313, 0.5068],
        [0.3137, 0.9069, 0.4720],
        [0.5993, 0.3635, 0.5686]])

In [72]:
# Apply the softmax function along dimension 1 of mat_b
mat_b.softmax(dim=1)

tensor([[0.3064, 0.2945, 0.3991],
        [0.0412, 0.8782, 0.0806],
        [0.4419, 0.1687, 0.3893]])